#!/bin/sh
if ! command -v openssl >/dev/null 2>&1 ; then
  echo "Error: Could not find openssl in \$PATH: $PATH"
  exit 1
fi

if test -f airspider.key; then
  echo "Error: airspider.key already exists"
  exit 1
fi

if test -f airspider.crt; then
  echo "Error: airspider.crt already exists"
  exit 1
fi

openssl req -new -newkey rsa:4096 -sha256 -x509 -days 365 -nodes -out airspider.crt -keyout airspider.key -subj "/CN=localhost"

chmod 600 airspider.crt
chmod 600 airspider.key
